language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install numpy
  - pip install pillow
  - pip install cython
  - pip install -r requirements.txt
  - cd ./src
  - python setup.py install
  - cd ../
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below