language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install numpy
  - pip install pillow
  - pip install cython
  - pip install -r requirements.txt
  - cd ./src
  - pip install .
  - cd ../
# command to run tests
script:
  - pytest